import type { Metadata } from "next";
import "./globals.css";
import { Box } from "@mui/material";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Next Photo Gallery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Box display="flex" flexDirection="column" minHeight="100vh">
          <Header />
          <Box component="main" flexGrow={1} py={4} px={2.5} >
            {children}
          </Box>
          <Footer />
        </Box>
      </body>
    </html>
  );
}
